### PR TITLE
👩‍💻Integration specs for views and ⚙ fix n+1 problems

### PR DESCRIPTION
**Pull request by hydaline-code**
Hello , 👋 in this milestone we : 
✅ Solved N+1 problem is solved when fetching all posts and their comments for a users 
Capture PNG1
Capture PNG3
✅Use Capybara to write integration tests for each view in the project for the user and the posts .
 Kindly ♻ Thank .

### CODE REVIEW

**Comment by rloterh** [comment]
Hi @hydaline-code 

Can you kindly add a professional ReadMe to you project using [this template](https://github.com/microverseinc/readme-template) ASAP!

Standing by..cheers!

**Comment by hydaline-code** [comment]
Hi, @rloterh 

Readme updated

**Comment by rloterh** [comment]
Hi @hydaline-code 

Again, lets improve the ReadMe by removing or updating the underlined:

image

**Comment by hydaline-code** [comment]
Hello @rloterh 
Update done 👍

**Comment by rloterh** [comment]
Hi @hydaline-code 

Still showing, under the _Key Features_, can you check once more?

image

**Comment by rloterh** [comment]
Hi @hydaline-code Kindly ensure to commit and push the changes so that it reflects on your repository..cheers

**Review by rloterh — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi Hydaline,  

**Blog app - integration specs for views and fix n+1 problems** is complete! 🏁 
 Congratulations!  🎉💯🌟 

## Highlights 🎯 
🎲 N + 1 problem addressed!
🎲 Added required integration specs and tests are passing!
🎲 Good ReadMe!

## Optional suggestions 🧰 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

**You can also consider:**
Let's make the ReadMe stand out even better by including instructions under the _Getting Started_ section, on how to run test cases for the app, for instance, using the command `rspec`.

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
